---
# tasks file for pkrole
- name: i want to install webserver on redhat
  yum:
   name: httpd
   state: present

- name: i want to start webserver on redhat  
  service:
     name: httpd
     state: started